name: Deploy static content to Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'projects/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'projects/**'
  workflow_dispatch:

concurrency:
  group: docs-main-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Docusaurus Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
            pixi-version: v0.53.0
            cache: true
            frozen: true
      - run: pixi run -e docs --frozen docs-build

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build'

  deploy:
      name: Deploy to GitHub Pages
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
